# : Manager {{{

[manager]
cwd = { fg = "#7aa2f7" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#f7768e", bold = true, italic = true, underline = true }
find_position = { fg = "#bb9af7", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#9ece6a", bg = "#9ece6a" }
marker_cut      = { fg = "#e0af68", bg = "#f7768e" }
marker_marked   = { fg = "#7aa2f7", bg = "#7dcfff" }
marker_selected = { fg = "#e0af68", bg = "#e0af68" }

# Tab
tab_active = { bg = "#282C34", fg = "#7aa2f7" }
tab_inactive = {}
tab_width    = 1

# Count
count_copied   = { fg = "#414868", bg = "#9ece6a" }
count_cut      = { fg = "#414868", bg = "#e0af68" }
count_selected = { fg = "#414868", bg = "#7aa2f7" }

# Border
border_symbol = "│"
border_style  = { fg = "#414868" }

# : }}}

# : Mode {{{
[mode]
normal_main = { fg = "#414868", bg = "#7aa2f7", bold = true }  # Darkened black on Blue
normal_alt  = { fg = "#7aa2f7", bg = "#414868", bold = true }  # Darkened black on Blue
select_main = { fg = "#414868", bg = "#9ece6a", bold = true }  # Darkened black on Green
select_alt  = { fg = "#9ece6a", bg = "#414868", bold = true }  # Darkened black on Green
unset_main  = { fg = "#414868", bg = "#bb9af7", bold = true }  # Darkened black on Magenta
unset_alt   = { fg = "#bb9af7", bg = "#414868", bold = true }  # Darkened black on Magenta
# : }}}


# : Status {{{

[status]
# separator_open  = ""
# separator_close = ""
separator_open  = ""
separator_close = ""
# separator_style = { fg = "#c6d0f5", bg = "#414868" }
separator_style = { fg = "#c6d0f5", bg = "#414868" }

# Progress
progress_label  = { fg = "#a9b1d6", bold = true }
progress_normal = { fg = "#7aa2f7", bg = "#414868" }
progress_error  = { fg = "#f7768e", bg = "#414868" }

# Permissions
perm_type  = { fg = "#7aa2f7" }  # Blue
perm_read  = { fg = "#9ece6a" }  # Green
perm_write = { fg = "#e0af68" }  # Yellow
perm_exec  = { fg = "#f7768e" }  # Red
perm_sep   = { fg = "#bb9af7" }  # Magenta

# : }}}


# : Select {{{

[select]
border   = { fg = "#7aa2f7" }
active   = { fg = "#bb9af7", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#7aa2f7" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[completion]
border = { fg = "#7aa2f7" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#7aa2f7" }
title   = {}
hovered = { fg = "#bb9af7", underline = true }

# : }}}
# : Which {{{

[which]
# mask            = { bg = "#25252D" }
cand            = { fg = "#9ece6a" }
rest            = { fg = "#a9b1d6" }
desc            = { fg = "#bb9af7" }
separator       = "  "
separator_style = { fg = "#626880" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#9ece6a" }
run     = { fg = "#bb9af7" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#a9b1d6", bg = "#c6d0f5" }

# : }}}


# : Notify {{{

[notify]
title_info  = { fg = "#9ece6a" }
title_warn  = { fg = "#f7768e" }
title_error = { fg = "#e0af68" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Directory
	{ mime = "inode/directory", fg = "#7aa2f7", bold = true },

	# Images
	{ mime = "image/*", fg = "#e0af68" },

	# Media
	{ mime = "video/*", fg = "#f7768e" },
	{ mime = "audio/*", fg = "#bb9af7" },

	# Archives
	{ mime = "application/zip",             fg = "#f7768e" },
	{ mime = "application/x-tar",           fg = "#f7768e" },
	{ mime = "application/x-bzip*",         fg = "#f7768e" },
	{ mime = "application/x-bzip2",         fg = "#f7768e" },
	{ mime = "application/x-7z-compressed", fg = "#f7768e" },
	{ mime = "application/x-rar",           fg = "#f7768e" },
	{ mime = "application/x-xz",            fg = "#f7768e" },

	# Documents
	{ mime = "application/doc",   fg = "#9ece6a" },
	{ mime = "application/pdf",   fg = "#9ece6a" },
	{ mime = "application/rtf",   fg = "#9ece6a" },
	{ mime = "application/vnd.*", fg = "#9ece6a" },

	# Fallback
	{ name = "*", fg = "#c6d0f5" },
	{ name = "*/", fg = "#7aa2f7" }
]

# : }}}
